In [58]:
# importing all the important libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('Placement_Data_Full_Class.csv')

   Display random 5 rows

In [4]:
df.sample(5)

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
185    186      F  88.00  Central   72.0  Central   Science      78.0   
153    154      M  49.00   Others   59.0   Others   Science      65.0   
25      26      F  52.58   Others   54.6  Central  Commerce      50.2   
110    111      F  69.50  Central   70.0  Central   Science      72.0   
196    197      M  72.00   Others   63.0   Others   Science      77.5   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
185     Others     No     82.0         Mkt&HR  71.43      Placed  252000.0  
153   Sci&Tech    Yes     86.0        Mkt&Fin  62.48      Placed  340000.0  
25   Comm&Mgmt    Yes     76.0        Mkt&Fin  65.33  Not Placed       NaN  
110   Sci&Tech     No     57.2         Mkt&HR  54.80      Placed  250000.0  
196   Sci&Tech    Yes     78.0        Mkt&Fin  54.48      Placed  250000.0

Dataset shaape


In [6]:
df.shape

(215, 15)

In [8]:
print("Number of Rows",df.shape[0])
print("Number of Columns",df.shape[1])

Number of Rows 215
Number of Columns 15


Dataset Info

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


Checking null values in dataset

In [11]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

Overall statstics of dataset

In [12]:
df.describe()

sl_no       ssc_p       hsc_p    degree_p     etest_p       mba_p  \
count  215.000000  215.000000  215.000000  215.000000  215.000000  215.000000   
mean   108.000000   67.303395   66.333163   66.370186   72.100558   62.278186   
std     62.209324   10.827205   10.897509    7.358743   13.275956    5.833385   
min      1.000000   40.890000   37.000000   50.000000   50.000000   51.210000   
25%     54.500000   60.600000   60.900000   61.000000   60.000000   57.945000   
50%    108.000000   67.000000   65.000000   66.000000   71.000000   62.000000   
75%    161.500000   75.700000   73.000000   72.000000   83.500000   66.255000   
max    215.000000   89.400000   97.700000   91.000000   98.000000   77.890000   

              salary  
count     148.000000  
mean   288655.405405  
std     93457.452420  
min    200000.000000  
25%    240000.000000  
50%    265000.000000  
75%    300000.000000  
max    940000.000000

EDA

In [14]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

How many students got placed

In [15]:
df['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [16]:
df['status'].value_counts()

Placed        148
Not Placed     67
Name: status, dtype: int64

Could you display the top 5 sci&tech students placed according to their salary?

In [25]:
df[(df['degree_t']=='Sci&Tech' ) & (df['status']=='Placed')].sort_values(by='salary',ascending=False).head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b    hsc_s  degree_p  \
150    151      M  71.00  Central  58.66  Central  Science     58.00   
77      78      M  64.00   Others  80.00   Others  Science     65.00   
163    164      M  63.00   Others  67.00   Others  Science     64.00   
174    175      M  73.24   Others  50.83   Others  Science     64.27   
53      54      M  80.00   Others  70.00   Others  Science     72.00   

     degree_t workex  etest_p specialisation  mba_p  status    salary  
150  Sci&Tech    Yes     56.0        Mkt&Fin  61.30  Placed  690000.0  
77   Sci&Tech    Yes     69.0        Mkt&Fin  57.65  Placed  500000.0  
163  Sci&Tech     No     75.0        Mkt&Fin  66.46  Placed  500000.0  
174  Sci&Tech    Yes     64.0        Mkt&Fin  66.23  Placed  500000.0  
53   Sci&Tech     No     87.0         Mkt&HR  71.04  Placed  450000.0

        Data Preprocessing

In [26]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [50]:
df = df.drop(['sl_no','salary'],axis=1)

Encoding  the categorical column

In [51]:
print(df['gender'].unique())
print(df['ssc_b'].unique())
print(df['hsc_b'].unique())
print(df['hsc_s'].unique())
print(df['degree_t'].unique())
print(df['specialisation'].unique())
print(df['status'].unique())
print(df['workex'].unique())

[1 0]
[1 0]
[1 0]
[1 2 0]
[2 0 1]
[1 0]
[1 0]
[0 1]


In [52]:
le=LabelEncoder()
cols=['gender','ssc_b','hsc_b','hsc_s','degree_t','specialisation','status','workex']
df[cols]=df[cols].apply(le.fit_transform)

Store Feature Matrix In X and Response(Target) In Vector y

In [53]:
X=df.drop('status',axis=1)
y=df['status']

Splitting The Dataset Into The Training Set And Test Set

In [54]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42) 

Importing the models

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score


Model Training

In [59]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
print(np.mean(cross_val_score(lr,X,y,scoring='accuracy',cv=10)))

svm = svm.SVC()
svm.fit(X_train,y_train)
print(np.mean(cross_val_score(svm,X,y,scoring='accuracy',cv=10)))

knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
print(np.mean(cross_val_score(knn,X,y,scoring='accuracy',cv=10)))

dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
print(np.mean(cross_val_score(dt,X,y,scoring='accuracy',cv=10)))

rf=RandomForestClassifier()
rf.fit(X_train,y_train)
print(np.mean(cross_val_score(rf,X,y,scoring='accuracy',cv=10)))

gb=GradientBoostingClassifier()
gb.fit(X_train,y_train)
print(np.mean(cross_val_score(gb,X,y,scoring='accuracy',cv=10)))

c:\Users\singh_anik\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\singh_anik\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

0.8701298701298701
0.8367965367965369
0.8463203463203464
0.7716450216450216
0.8744588744588745
0.8326839826839827


Prediction on test data

In [60]:
y_pred1 = lr.predict(X_test)
y_pred2 = svm.predict(X_test)
y_pred3 = knn.predict(X_test)
y_pred4 = dt.predict(X_test)
y_pred5 = rf.predict(X_test)
y_pred6 = gb.predict(X_test)

    Evaluating the Algorithms

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
score1=accuracy_score(y_test,y_pred1)
score2=accuracy_score(y_test,y_pred2)
score3=accuracy_score(y_test,y_pred3)
score4=accuracy_score(y_test,y_pred4)
score5=accuracy_score(y_test,y_pred5)
score6=accuracy_score(y_test,y_pred6)

In [64]:
print(score1,score2,score3,score4,score5,score6)

0.8837209302325582 0.7674418604651163 0.7906976744186046 0.8372093023255814 0.7906976744186046 0.813953488372093


    Prediction on New Data

In [65]:
new_data = pd.DataFrame({
    'gender':0,
    'ssc_p':67.0,
    'ssc_b':0,
    'hsc_p':91.0,
    'hsc_b':0,
    'hsc_s':1,
    'degree_p':58.0,
    'degree_t':2,
    'workex':0,
    'etest_p':55.0,
     'specialisation':1,
    'mba_p':58.8,   
},index=[0])

In [68]:
lr= LogisticRegression()
lr.fit(X,y)



c:\Users\singh_anik\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [69]:
rf= RandomForestClassifier()
rf.fit(X,y)

RandomForestClassifier()

In [73]:
p=lr.predict(new_data)
prob1=lr.predict_proba(new_data)
if p==1:
    print('Placed')
    print(f"You will be placed with probability of {prob1[0][1]:.2f}")
else:
    print("Not-placed")

Placed
You will be placed with probability of 0.94


In [74]:
p1=rf.predict(new_data)
prob2=rf.predict_proba(new_data)
if p1==1:
    print('Placed')
    print(f"You will be placed with probability of {prob2[0][1]:.2f}")
else:
    print("Not-placed")

Placed
You will be placed with probability of 0.73


In [75]:
prob1

array([[0.0557864, 0.9442136]])

In [76]:
prob2

array([[0.27, 0.73]])

Save Model Using Joblib

In [77]:
import joblib

In [78]:
joblib.dump(lr,'C_p')

['C_p']

In [83]:
model=joblib.load('C_p')

In [84]:
model.predict(new_data)

array([1], dtype=int64)

In [86]:
from tkinter import *
import joblib
import numpy as np
from sklearn import *
import tkinter.font as font
import pandas as pd

def show_entry_fields():
    text = clicked.get()
    if text == "Male":
        p1=1
        print(p1)
    else:
        p1=0
        print(p1)
    p2=float(e2.get())
    text = clicked1.get()
    if text == "Central":
        p3=1
        print(p3)
    else:
        p3=0
        print(p3)
    p4=float(e4.get())
    text = clicked6.get()
    if text == "Central":
        p5=1
        print(p3)
    else:
        p5=0
        print(p3)
    text = clicked2.get()
    if text == "Science":
        p6=2
        print(p6)
    elif text == "Commerce":
        p6=1
        print(p6)
    else:
        p6=0
        print(p6)
    p7=float(e7.get())
    text = clicked3.get()
    if text == "Sci&Tech":
        p8=2
        print(p8)
    elif text=="Comm&Mgmt":
        p8=1
        print(p8)
    else:
        p8=0
        print(p8)
    text = clicked4.get()
    if text == "Yes":
        p9=1
        print(p3)
    else:
        p9=0
        print(p3)
    p10=float(e10.get())
    text = clicked5.get()
    if text == "Mkt&HR":
        p11=1
        print(p11)
    else:
        p11=0
        print(p11)
    p12=float(e12.get())

    model = joblib.load('C_p')
    new_data = pd.DataFrame({
    'gender':p1,
    'ssc_p':p2,
    'ssc_b':p3,
    'hsc_p':p4,
    'hsc_b':p5,
    'hsc_s':p6,
    'degree_p':p7,
    'degree_t':p8,
    'workex':p9,
    'etest_p':p10,
     'specialisation':p11,
    'mba_p':p12,   
},index=[0])
    result=model.predict(new_data)
    result1=model.predict_proba(new_data)
    
    if result[0] == 0:
        Label(master, text="Can't Placed").grid(row=31)
    else:
        Label(master, text="Student Will be Placed With Probability of",font=("Arial", 15)).grid(row=31)
        Label(master, text=round(result1[0][1],2)*100,font=("Arial", 15)).grid(row=33)
        Label(master, text="Percent",font=("Arial", 15)).grid(row=34)

master = Tk()
master.title("Campus Placement Prediction System")


label = Label(master, text = "Campus Placement Prediction System"
                          , bg = "green", fg = "white",font=("Arial", 20)) \
                               .grid(row=0,columnspan=2)


Label(master, text="Gender",font=("Arial", 15)).grid(row=1)
Label(master, text="Secondary Education percentage- 10th Grade",font=("Arial", 15)).grid(row=2)
Label(master, text="Board of Education",font=("Arial", 15)).grid(row=3)
Label(master, text="Higher Secondary Education percentage- 12th Grade",font=("Arial", 15)).grid(row=4)
Label(master, text="Board of Education",font=("Arial", 15)).grid(row=5)
Label(master, text="Specialization in Higher Secondary Education",font=("Arial", 15)).grid(row=6)
Label(master, text="Degree Percentage",font=("Arial", 15)).grid(row=7)
Label(master, text="Under Graduation(Degree type)- Field of degree education",font=("Arial", 15)).grid(row=8)
Label(master, text="Work Experience",font=("Arial", 15)).grid(row=9)
Label(master, text="Enter test percentage",font=("Arial", 15)).grid(row=10)
Label(master, text="branch specialization",font=("Arial", 15)).grid(row=11)
Label(master, text="MBA percentage",font=("Arial", 15)).grid(row=12)
clicked = StringVar()
options = ["Male","Female"]

clicked1 = StringVar()
options1 = ["Central","Others"]

clicked2 = StringVar()
options2 = ["Science","Commerce","Arts"]

clicked3 = StringVar()
options3 = ["Sci&Tech","Comm&Mgmt","Others"]

clicked4 = StringVar()
options4 = ["Yes","No"]

clicked5 = StringVar()
options5 = ["Mkt&HR","Mky&Fin"]

clicked6 = StringVar()
options6 = ["Central","Others"]
e1 = OptionMenu(master , clicked , *options )
e1.configure(width=13)
e2 = Entry(master)
e3 = OptionMenu(master , clicked1 , *options1 )
e3.configure(width=13)
e4 = Entry(master)
e5 = OptionMenu(master , clicked6 , *options6)
e5.configure(width=13)
e6 = OptionMenu(master , clicked2 , *options2)
e6.configure(width=13)
e7 = Entry(master)
e8 = OptionMenu(master , clicked3 , *options3)
e8.configure(width=13)
e9 = OptionMenu(master , clicked4 , *options4)
e9.configure(width=13)
e10 = Entry(master)
e11 = OptionMenu(master , clicked5 , *options5)
e11.configure(width=13)
e12 = Entry(master)


e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3, column=1)
e4.grid(row=4, column=1)
e5.grid(row=5, column=1)
e6.grid(row=6, column=1)
e7.grid(row=7, column=1)
e8.grid(row=8, column=1)
e9.grid(row=9, column=1)
e10.grid(row=10, column=1)
e11.grid(row=11, column=1)
e12.grid(row=12, column=1)
buttonFont = font.Font(family='Helvetica', size=16, weight='bold')
Button(master, text='Predict',height= 1, width=8,activebackground='#00ff00',font=buttonFont,bg='black', fg='white',command=show_entry_fields).grid()

mainloop()

1
0
0
2
2
0
1
1
0
0
2
2
0
1
